### PR TITLE
Created a basic keyboard mock-up and score input fields.

### PR DESCRIPTION
**Pull request by VeronikaHar**

### CODE REVIEW

**Comment by pncifra** [comment]
Howdy! you'll want to update the pull request to merge into master and not into the pncifra:VH_scorekeeper branch. So the process would be, make sure you've got the latest version of master, create a branch off the latest of master then open a pull request against master from your new branch. Once you do that, for myself, I'll make sure I get updated locally with the latest from master 
Screen Shot 2020-01-04 at 1 57 45 AM

**Comment by VeronikaHar** [comment]
Hey!

Yeah, it's still all a bit confusing for me.
I did take the latest master file and followed these article about how to do collaboration:
https://code.tutsplus.com/tutorials/how-to-collaborate-on-github--net-34267
What I thought is: I haven't yet finished the screen, I'm just submitting the progress and since it's not a finished screen, I'm submitting it to the scorekeeper branch, not master. I thought we'll just merge the VH_scorekeeper branch with master after it's fully functional.
But if you prefer to have it pulled into master while not finished, I can do it.



Best regards,
Veronika



-------- Original message --------

**Comment by pncifra** [comment]
Yups that's fine. We'll be making small incremental changes into master. It'll prevent any major conflicts in the future since I can update my local branch to be up to date with the changes in master. 👍

**Comment by VeronikaHar** [comment]
Sure! Done:)

**Pull request merged**
